### ISSUE TITLE
compression fails when using javascript file containing utf-8 characters 

### ISSUE THREAD

**Issue by ghost** [documentcloud/jammit#91]
platform:
- ruby 1.9.2
- rails 3.0.1
- jammit 0.5.4

Compression of application.js file:

```
$(function() {
    var a = "ąść";
});
```

results in error (using YUI):
    YUI::Compressor::RuntimeError in JammitController#package
    compression failed

using Closure:
    Encoding::UndefinedConversionError in JammitController#package
    "\xC4" from ASCII-8BIT to UTF-8

Here is my assest.rb file:
    package_assets:         always          # (on, off, always)
    embed_assets:           off          # (on, off, datauri)
    compress_assets:        on          # (on, off)
    gzip_assets:            on          # (on, off)
    template_function:      on  # (defaults to the built-in micro-templating)
    package_path:           packages    # (defaults to assets)
    javascript_compressor:  closure     # (yui, closure)

```
javascripts:
  workspace:
    - public/javascripts/application.js

stylesheets:
  workspace:
    - public/stylesheets/*.css
```
